### ISSUE TITLE
Support editing sent webhook messages

### ISSUE THREAD

**Issue by satanskitty** [Sarrus1/DiscordWebhookAPI#2]
https://discord.com/developers/docs/resources/webhook#edit-webhook-message

**Comment by Sarrus1** [comment]
Implemented in c5d74520f4e3ce1f5793b058b34a5df2e43fbf6e.
Please find an example [here](https://github.com/Sarrus1/DiscordWebhookAPI/blob/98db4ebbd7ad525f889d93c40ce7bc623edada8b/example.sp#L136-L176)

Notice that the response status check has [changed when executing a webhook](https://github.com/Sarrus1/DiscordWebhookAPI/blob/98db4ebbd7ad525f889d93c40ce7bc623edada8b/example.sp#L129).
