### ISSUE TITLE
[REQUEST] Components

### ISSUE THREAD

**Issue by K4ryuu** [Sarrus1/DiscordWebhookAPI#3]
Dear Sarrus,
First of all I would like to thank you the include! In the other hand I would like to ask, if components (buttons under messages) could be Added?

Greetings,
Karyuu

**Comment by Sarrus1** [comment]
Hi, glad you like the include!
Unfortunately, buttons are not part of Discord's webhook API, only the "general" API, which this include does not cover.
However, I am sure some other sourcepawn include provide this feature.
