### ISSUE TITLE
Webhook doesnt respect sorting in code

### ISSUE THREAD

**Issue by Rushaway** [Sarrus1/DiscordWebhookAPI#4]
Let say i have kind of code.
I did it this way bcs i need to have few parts send. I need them to be in order : Pt1, Pt2, ...
```
char szWebhookURL[1000];
g_cvWebhook.GetString(szWebhookURL, sizeof szWebhookURL);

char sPt1[4096];
Format(sPt1, sizeof(sPt1), "```Part 1 on my text here```");
Webhook webhook = new Webhook(sPt1);
webhook.Execute(szWebhookURL, OnWebHookExecuted);
delete webhook;

char sPt2[4096];
Format(sPt2, sizeof(sPt2), "Part 2 here");
Webhook webhook2 = new Webhook(sPt2);
webhook2.Execute(szWebhookURL, OnWebHookExecuted);
delete webhook2;

char sPt3[4096];
Format(sPt3, sizeof(sPt3), "Part 3 here");
Webhook webhook3 = new Webhook(sPt3);
webhook3.Execute(szWebhookURL, OnWebHookExecuted);
delete webhook3;
```
Depending the numbers of characters (from Format) in the Webhook part, some of them will be sent first.
Any way to sort messages ?

**Comment by Sarrus1** [comment]
Hello, it seems that the order of the POST requests RIPext makes in the background is not guaranteed.
What you can do is store your webhooks in an array, and execute them from the callback function of the request `OnWebhookExecuted`.
Have a static counter in the callback which gets incremented and points to the correct location in the array for the next webhook to be sent.
