### ISSUE TITLE
[Request] Retry time

### ISSUE THREAD

**Issue by Rushaway** [Sarrus1/DiscordWebhookAPI#5]
Is it possible to make a retry timer if the status does not return as OK ?
Exemple:
```
if (response.Status != HTTPStatus_OK)
    {
        RetrySendMessages();
    }
```

**Comment by Sarrus1** [comment]
Hello,

I would rather leave this implementation to the user, as there is no reason for the webhook to fail if the discord API is not down and the message is properly formatted.
